# Generated by Django 5.0.6 on 2024-06-26 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_aboutpage_contactpage_delete_staticpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='content',
        ),
    ]
